trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'myconsoleapp'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    docker build -t $(imageName):$(Build.BuildId) .
    docker tag $(imageName):$(Build.BuildId) myacr.azurecr.io/$(imageName):$(Build.BuildId)
  displayName: 'Build Docker Image'

- task: Docker@2
  inputs:
    containerRegistry: 'myACR'
    repository: '$(imageName)'
    command: 'push'
    tags: |
      $(Build.BuildId)

- task: AzureCLI@2
  inputs:
    azureSubscription: 'myAzureSubscription'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az containerapp update \
        --name mycontainerapp \
        --resource-group myResourceGroup \
        --image myacr.azurecr.io/$(imageName):$(Build.BuildId)
  displayName: 'Deploy to Azure Container App'
